"""create kompare core models

Revision ID: 61c846c055cd
Revises: 
Create Date: 2026-08-19 18:36:27.152003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c846c055cd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('CRYPTO', 'GIFTCARD', 'FX', name='market_category'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_category'), 'assets', ['category'], unique=False)
    op.create_index(op.f('ix_assets_code'), 'assets', ['code'], unique=True)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('fetch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('QUIDAX', name='provider_name'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', name='fetch_run_status'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('records_fetched', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fetch_runs_id'), 'fetch_runs', ['id'], unique=False)
    op.create_index(op.f('ix_fetch_runs_provider'), 'fetch_runs', ['provider'], unique=False)
    op.create_index(op.f('ix_fetch_runs_status'), 'fetch_runs', ['status'], unique=False)
    op.create_table('provider_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('QUIDAX', name='provider_name'), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('provider_symbol', sa.String(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_symbol', name='uq_provider_asset_symbol')
    )
    op.create_index(op.f('ix_provider_assets_asset_id'), 'provider_assets', ['asset_id'], unique=False)
    op.create_index(op.f('ix_provider_assets_id'), 'provider_assets', ['id'], unique=False)
    op.create_index(op.f('ix_provider_assets_provider'), 'provider_assets', ['provider'], unique=False)
    op.create_index(op.f('ix_provider_assets_provider_symbol'), 'provider_assets', ['provider_symbol'], unique=False)
    op.create_table('raw_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('QUIDAX', name='provider_name'), nullable=False),
    sa.Column('fetch_run_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('API', 'HTML', 'JSON', 'DOCUMENT', name='raw_source_type'), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fetch_run_id'], ['fetch_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_records_external_id'), 'raw_records', ['external_id'], unique=False)
    op.create_index(op.f('ix_raw_records_fetch_run_id'), 'raw_records', ['fetch_run_id'], unique=False)
    op.create_index(op.f('ix_raw_records_id'), 'raw_records', ['id'], unique=False)
    op.create_index(op.f('ix_raw_records_provider'), 'raw_records', ['provider'], unique=False)
    op.create_index(op.f('ix_raw_records_source_type'), 'raw_records', ['source_type'], unique=False)
    op.create_table('kyc_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('QUIDAX', name='provider_name'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fetch_run_id', sa.Integer(), nullable=True),
    sa.Column('raw_record_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fetch_run_id'], ['fetch_runs.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_profiles_fetch_run_id'), 'kyc_profiles', ['fetch_run_id'], unique=False)
    op.create_index(op.f('ix_kyc_profiles_id'), 'kyc_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_kyc_profiles_provider'), 'kyc_profiles', ['provider'], unique=False)
    op.create_index(op.f('ix_kyc_profiles_raw_record_id'), 'kyc_profiles', ['raw_record_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('QUIDAX', name='provider_name'), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('provider_asset_id', sa.Integer(), nullable=True),
    sa.Column('fetch_run_id', sa.Integer(), nullable=True),
    sa.Column('raw_record_id', sa.Integer(), nullable=True),
    sa.Column('quote_type', sa.Enum('SPOT', 'BUY', 'SELL', 'MARKET', name='quote_type'), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('quote_currency', sa.String(), nullable=False),
    sa.Column('buy_rate', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('sell_rate', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('mid_rate', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('market_price', sa.Numeric(precision=24, scale=8), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['fetch_run_id'], ['fetch_runs.id'], ),
    sa.ForeignKeyConstraint(['provider_asset_id'], ['provider_assets.id'], ),
    sa.ForeignKeyConstraint(['raw_record_id'], ['raw_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_asset_id'), 'quotes', ['asset_id'], unique=False)
    op.create_index(op.f('ix_quotes_base_currency'), 'quotes', ['base_currency'], unique=False)
    op.create_index(op.f('ix_quotes_fetch_run_id'), 'quotes', ['fetch_run_id'], unique=False)
    op.create_index(op.f('ix_quotes_id'), 'quotes', ['id'], unique=False)
    op.create_index(op.f('ix_quotes_provider'), 'quotes', ['provider'], unique=False)
    op.create_index(op.f('ix_quotes_provider_asset_id'), 'quotes', ['provider_asset_id'], unique=False)
    op.create_index(op.f('ix_quotes_quote_currency'), 'quotes', ['quote_currency'], unique=False)
    op.create_index(op.f('ix_quotes_quote_type'), 'quotes', ['quote_type'], unique=False)
    op.create_index(op.f('ix_quotes_raw_record_id'), 'quotes', ['raw_record_id'], unique=False)
    op.create_table('kyc_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyc_profile_id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fiat_deposit_limit', sa.String(), nullable=True),
    sa.Column('fiat_withdrawal_limit', sa.String(), nullable=True),
    sa.Column('crypto_deposit_limit', sa.String(), nullable=True),
    sa.Column('crypto_withdrawal_limit', sa.String(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kyc_profile_id'], ['kyc_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_levels_id'), 'kyc_levels', ['id'], unique=False)
    op.create_index(op.f('ix_kyc_levels_kyc_profile_id'), 'kyc_levels', ['kyc_profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kyc_levels_kyc_profile_id'), table_name='kyc_levels')
    op.drop_index(op.f('ix_kyc_levels_id'), table_name='kyc_levels')
    op.drop_table('kyc_levels')
    op.drop_index(op.f('ix_quotes_raw_record_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_type'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_currency'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_provider_asset_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_provider'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_fetch_run_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_base_currency'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_asset_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_kyc_profiles_raw_record_id'), table_name='kyc_profiles')
    op.drop_index(op.f('ix_kyc_profiles_provider'), table_name='kyc_profiles')
    op.drop_index(op.f('ix_kyc_profiles_id'), table_name='kyc_profiles')
    op.drop_index(op.f('ix_kyc_profiles_fetch_run_id'), table_name='kyc_profiles')
    op.drop_table('kyc_profiles')
    op.drop_index(op.f('ix_raw_records_source_type'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_provider'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_id'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_fetch_run_id'), table_name='raw_records')
    op.drop_index(op.f('ix_raw_records_external_id'), table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_index(op.f('ix_provider_assets_provider_symbol'), table_name='provider_assets')
    op.drop_index(op.f('ix_provider_assets_provider'), table_name='provider_assets')
    op.drop_index(op.f('ix_provider_assets_id'), table_name='provider_assets')
    op.drop_index(op.f('ix_provider_assets_asset_id'), table_name='provider_assets')
    op.drop_table('provider_assets')
    op.drop_index(op.f('ix_fetch_runs_status'), table_name='fetch_runs')
    op.drop_index(op.f('ix_fetch_runs_provider'), table_name='fetch_runs')
    op.drop_index(op.f('ix_fetch_runs_id'), table_name='fetch_runs')
    op.drop_table('fetch_runs')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_code'), table_name='assets')
    op.drop_index(op.f('ix_assets_category'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
