services:
  app:
    container_name: kompare_app
    build:
      context: .
    command: ["/app/start.sh"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      PORT: 8000
